sonar.projectKey=aptio-api
sonar.projectName=Aptio API
sonar.projectVersion=1.0.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.libraries=target/dependency/*.jar

sonar.sourceEncoding=UTF-8
sonar.java.source=17

# Exclusions
sonar.exclusions=src/main/java/com/aptio/config/**,src/main/java/com/aptio/dto/**
